version: '3.7'
services:

  wallmart-ui:
    image: wallmart-ui:0.0.1
    container_name: angular-app
    # volumes:
      # - './:user/src/app'
    ports:
      - 80:80
    networks:
      - shared-net
    # command: >
      # bash -c "npm start"
    # links:
      # - wallmart-api
    depends_on:
      - wallmart-api

  wallmart-api:
    image: wallmart-api:0.0.1
    container_name: springboot-app
    depends_on:
      - mongodb
    # links:
      # - mongodb
    ports:
      - 8030:8030
    networks:
      - shared-net

  mongodb:
    image: mongo:4.4
    container_name: mongo-app
    restart: always
    environment:
      # MONGO_INITDB_ROOT_AUTHENTICATION-DATABASE: none
      # MONGO_INITDB_ROOT_HOST: localhost
      # MONGO_INITDB_USERNAME: wallmart
      # MONGO_INITDB_PASSWORD: wallmart1234
      MONGO_INITDB_DATABASE: wallmart
    ports:
      - 27017:27017
    networks:
      - shared-net
    volumes:
      - /data/db:/data/db

networks:
  shared-net:
    driver: bridge