version: '3.7'
services:

  mongodb:
    image: mongo:4.4
    container_name: mongo-app
    restart: always
    environment:
      MONGO_INITDB_DATABASE: wallmart
    ports:
      - 27017:27017
    networks:
      - shared-net
    volumes:
      - /data/db:/data/db

  wallmart-api:
    image: wallmart-api:0.0.1
    container_name: springboot-app
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 8030:8030
    networks:
      - shared-net

  wallmart-ui:
    image: wallmart-ui:0.0.1
    container_name: angular-app
    ports:
      - 80:80
    networks:
      - shared-net
    depends_on:
      - wallmart-api

networks:
  shared-net:
    driver: bridge